// <auto-generated />
using LAB_LTW_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAB_LTW_API.Migrations.BookAuthDb
{
    [DbContext(typeof(BookAuthDbContext))]
    [Migration("20240514014432_Create Auth Database")]
    partial class CreateAuthDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "004c7e80 - 7dfc - 44be - 8952 - 2c7130898655",
                            ConcurrencyStamp = "004c7e80 - 7dfc - 44be - 8952 - 2c7130898655",
                            Name = "Read",
                            NormalizedName = "READ"
                        },
                        new
                        {
                            Id = "71e282d3-76ca-485e-b094-eff019287fa5",
                            ConcurrencyStamp = "71e282d3-76ca-485e-b094-eff019287fa5",
                            Name = "Write",
                            NormalizedName = "WRITE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
